FROM node:20.2-alpine AS build

WORKDIR /app

# Copia los archivos del proyecto
COPY package*.json ./
RUN npm install

COPY . .

# Ejecuta el build (ajusta si usas otro comando)
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine

# Elimina contenido por defecto de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia los archivos construidos al servidor Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80